version: '3.1'

services:

  signup-web:
    image: dak4dotnet/signup-web:v5
    build:
      context: ..
      dockerfile: ./docker/prod-config/signup-web/Dockerfile

  signup-save-handler:
    image: dak4dotnet/save-handler:v3
    build:
      context: ..
      dockerfile: ./docker/prod-config/save-handler/Dockerfile