version: '3.1'

services:

  signup-web:
    image: dak4dotnet/signup-web:v3
    build:
      context: ..
      dockerfile: ./docker/metrics-runtime/signup-web/Dockerfile

  signup-save-handler:
    image: dak4dotnet/save-handler:v2
    build:
      context: ..
      dockerfile: ./docker/metrics-application/save-handler/Dockerfile

  signup-index-handler:
    image: dak4dotnet/index-handler:v2
    build:
      context: ..
      dockerfile: ./docker/metrics-application/index-handler/Dockerfile