apiVersion: apps/v1
kind: Deployment
metadata:
  name: save-handler
spec:
  selector:
    matchLabels:
      app: signup
      component: save-handler
  template:
    metadata:
      labels:
        app: signup
        component: save-handler
    spec:
      containers:
        - image: dak4dotnet/signup-save-handler-core:linux
          name: save-handler
          volumeMounts:
            - name: configs
              mountPath: "/app/configs"
              readOnly: true
      volumes:
        - name: configs
          configMap:
            name: save-handler-config
      nodeSelector:
        beta.kubernetes.io/os: linux
